travis:
  secure:
    BINSTAR_TOKEN: 1I5sY2QwgLaua5MVDeqwj7CxrxHUrQ4s83XZifpeQLSw11KAY0QaMCL9lh2+0PU206z6LAev/7mhPvIPQ+srm5HhhEhcr5bkNzXJeVDJNXNab4esIak3xDPTMrGzPvMO8opdu2vnTEOEh1sBG7BsccWtw7+iLleXVz2WALNaveyt4BqMZ5mEJIE7KurGSt5/44PN5MqNIfr1/ss4d85OlgWSuaJtk4hbzJbRLIqulABO/HFzqceoleUJ3QvlqZ6w0psakCXOilZ8JZqNOdt1sM3a0F5dQ9mQ9KdYj/AdJxAuyjIUf8LfT1xNWgdLJgOVG6KCslrFhmVwkM5HdKt37UlJWwpkIiNTC7V9G3T0h8YMwUQj9eWrefi772nEQWaWmJvV9F4y+q+uKdujefLrZFNBf/Qbb6Zdgm9x6yRz0QfdTNXFo45lyCvtDxMDspJDKV5vCXyO4zTir9CJResvRgDbImClVWvBxJz6OwbN/oBIA1jgjCdvr5tMXL/ELlI9ZoK1nswfZORzqT1pwfyfWbjltDnTMeBohgpzRhU5PM8AnNR6fXzjg/MA4HOSHz6atTsV3ZNS2aEfuxYspKOvx2fhLBLBXmvguSq/3/M+B5Vu0twokV4hyaUUqJ6TnzTmCxXJ5IKWXEVoAi+UiJ2ZQG5eDauAs2XtXg3XGR/4yiE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
