travis:
  secure:
    BINSTAR_TOKEN: nw8v2sh3lqGhGNCOPm5gD46wRSFBTNuYMzECtGq6Coijy0lX2Fzya29H3UvF1L/nqsNF6savlbvOjSYY3sVdS895+/Na8tmqQKmuQWWCxOruOuXSz6dcZ7fGJhcVgto1kyVQOF8jcjh/2kQtVjZ7G5vDO3GXJuf7xW5hAx7PmdkIu4NiW8vvIERsDhCz9TQ7TXEJXf1fjXxMG4MGnnVIpYTsa56fZaJt66n52Ozfp2DMp4viVxTBa8VEgKWzKtrwoCOwCPKBzEoaVxOVZsMsffux3LBt2Ht09aG52tl9NCNW2l78/N5Zdf253xiCFjhROCe2C+/q1n5AZzdnFfwR2JlvDWCJYUrkqwDK2jVbzW6lQ8RsZWGYAU/s6XdqTWGSP3Lz6c6/3KMsBAvbuQY/H7REwYKWooZiEV9t9TNu7Aa3FDWFjw2DPS5eZsivb8LNhQZ11264VB3Qgwx4c9DqgjYu0icbPYHZ2lwa9niLmTi5ufh4q3zXaFxT1V3PljV245FtoXDyt2EbCCxdaZIj2Z13APA+NPg70ki7w084KtL85rtg8j/rkvwu7zAXL2ZryodajHaIItX5TusC5vyNAFnWOJpxDB/obFXMVKqY4+UMjTTcyX0EA3L/bqGA9SVViWM1vgvRfppSfF1TaI/2cWeVPprnUf/9C01u8XCzVnM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
